services:
  www:
    build:
      dockerfile: d.briantakita.me.Dockerfile
    env_file:
      - .env
    expose:
      - "80"
      - "443"
      - "4100"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.briantakitame-www.loadbalancer.server.port=4100"
      - "traefik.http.routers.briantakitame-www.rule=Host(`briantakita.me`) || Host(`www.briantakita.me`)"
      - "traefik.http.routers.briantakitame-www.tls.certresolver=acme"
      - "traefik.http.middlewares.briantakitame-www.retry.attempts=4"
      - "traefik.http.middlewares.briantakitame-www.retry.initialinterval=100ms"
      - "traefik.http.routers.briantakitame-www.middlewares=briantakitame-www-https-redirect,briantakitame-www-host-redirect"
      - "traefik.http.middlewares.briantakitame-www-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.briantakitame-www-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.briantakitame-www-host-redirect.redirectregex.regex=^https://www.briantakita.me/(.*)"
      - "traefik.http.middlewares.briantakitame-www-host-redirect.redirectregex.replacement=https://briantakita.me/$${1}"
      - "traefik.http.middlewares.briantakitame-www-host-redirect.redirectregex.permanent=true"
    networks:
      - web
    volumes:
      - .:/app
    restart: on-failure
networks:
  web:
    external: true
